export const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL as string
export const NEXT_PUBLIC_CUSTOMERS_API_URL = process.env.NEXT_PUBLIC_CUSTOMERS_API_URL
export const NEXT_PUBLIC_AVATARS_URL = process.env.NEXT_PUBLIC_AVATARS_URL as string

export const CUSTOMERS_PAGINATION_RESULTS_PER_PAGE = 9
